Add controllers
Sintsoft/java-shareit pull request #2
Opened 2023-05-30 16:41 UTC by Sintsoft

2023-05-31 07:16 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть несколько замечаний, которые необходимо исправить!

Желаю удачи!

2023-05-31 07:16 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/utility/storage/AppStorage.java
> +}
Не вижу большого преимкщества для объединения этих компонентов в один класс. 

Понятно, что ты не хочешь импортить эти поля по  отдельности, но представь, что будет, если у тебя будет 100 хранилищ, этот класс станет сопоставим по размерам с размерами хранилищ. И получится так называемый `GOD`-объект, это антипаттерн ООП.

https://en.wikipedia.org/wiki/God_object

2023-05-31 07:16 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl2.java
> +public class UserServiceImpl2 implements UserService {
Это не сервис, а хранилище полуается, не ясно, зачем нужна такая реализация.
К тому же я крайний противник цифровых идентификаторов в названии

2023-05-31 07:16 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/utility/storage/CRUDStorage.java
> +public class CRUDStorage<T extends Entity> {
А почему у хранилища нет интерфейса?

В идеале должно быть так:

1. Интерфейс для каждого типа хранилища
2. Абстрактный класс, который собирает в себя общие методы
3. Класс-наследник, реализующий специализированные методы, задекларированные в интерфейсе для конкретной абстракции. Так как очевидно, что нам могут потребоваться дополнительные методы для различных объектов.

2023-05-31 07:16 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/User.java
> +                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {
Аннотация `email` проверяет недостаточно точно?

2023-06-01 21:40 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/user/User.java
> +                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$")) {
К сожалению да, иногда она пропускает некорректные email

2023-06-02 07:29 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-06-05 06:07 UTC, merged