Add bookings
Sintsoft/java-shareit pull request #3
Opened 2023-06-25 12:48 UTC by Sintsoft

Сделал по 14-му спринту. Если огрехи не критичные можно исправить их в следующим спринте?

2023-06-26 08:25 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторые замечания, которые необходимо исправить!

Желаю удачи!

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +create schema if not exists shareit;
Не хотелось бы, чтобы при каждом релизе приложения это происходило, тогда все данные наших пользователей будут удалены, что крайне неправильно. Может быть можно не удалять всю схему целиком?

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +  email CHARACTER VARYING NOT NULL,
Необходимо накладывать какие-то вменяемые ограничения на размер текстовых колонок.
Например у адреса электронной почты есть ограничения по стандарту, которые указаны в `RFC`. Максимальная допустимая длина - 320 символов, реально возможная длина - 255 символов. 

Это касается и всех колонок ниже, на них можно и нужно наложить разумные ограничения.

https://www.rfc-editor.org/errata/eid1690

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +	available BOOLEAN,
Думаю, что это поле не может быть `null`

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +  end_date TIMESTAMP WITHOUT TIME zone,
Могут быть `null`?

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +  comment_text CHARACTER VARYING,
Кажется, что не может быть `null`, иначе какой смысл записи в таблице? Пустой комментарий?

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +  created TIMESTAMP WITHOUT TIME zone,
Могут ли эти поля быть `NULL`?

2023-06-26 08:25 UTC, LexLippi commented on src/main/resources/schema.sql
> +  booker_id BIGINT references shareit.users (id),
Могут быть `null`?

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private BookingStatus status;
Надо прописать `nullable = false`, если в колонке не допустимы нулевые значения

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceWithDBRepo.java
> +        } catch (NullPointerException ex) {
В идеале, не допускать таких ошибок, и предотвращать их проверками, а не с помощью `try-catch`, так как это будет работать быстрее. Однако в данном случае это не настолько приоритетно, можно не исправлять

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/vault/BookingStorage.java
> +                .filter(x -> filterBookings(x, status));
несмотря на то, что это лямбда, это полноценная переменная, и называть ее надо соответствующе

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/vault/BookingStorage.java
> +    public Booking updateBooking(Booking booking) {
А это почему не `Transactional`?

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/comment/model/Comment.java
> +    @Column(name = "created")
Аналогично про `nullable`

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/comment/vault/CommentStorage.java
> +            return comments;
Зачем в две строки непонятно

2023-06-26 08:25 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/vault/UserStorage.java
> +        return optionalUser.get();
1. По возможности лучше не использовать `.get()`, так как это убивает весь смысл `Optional`, и всю ленивость вычислений
2. В твоем случае идеально подходит метод `.orElseThrow()`

2023-06-26 19:38 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/comment/vault/CommentStorage.java
> +            return comments;
Дебажил, исправил

2023-06-26 19:38 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/booking/vault/BookingStorage.java
> +    public Booking updateBooking(Booking booking) {
исправлено

2023-06-26 19:48 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/user/vault/UserStorage.java
> +        return optionalUser.get();
Не знал, спасибо.

2023-06-26 19:49 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/booking/vault/BookingStorage.java
> +                .filter(x -> filterBookings(x, status));
исправлено

2023-06-26 19:49 UTC, Sintsoft commented on src/main/resources/schema.sql
> +  comment_text CHARACTER VARYING,
исправлено

2023-06-26 19:49 UTC, Sintsoft commented on src/main/resources/schema.sql
> +  created TIMESTAMP WITHOUT TIME zone,
исправлено

2023-06-26 19:49 UTC, Sintsoft commented on src/main/resources/schema.sql
> +  booker_id BIGINT references shareit.users (id),
исправлено

2023-06-26 19:54 UTC, Sintsoft commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private BookingStatus status;
Добавил, падает

2023-06-27 12:50 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2023-06-27 14:10 UTC, merged